.catalog:
    name: "Convoy GlusterFS"
    version: "v0.3-dev2"
    description: "Convoy GlusterFS - Docker volume plugin"
    questions:
     - variable: "VOLUME_POOL"
       description: "Name of the GlusterFS Volume"
       label: "GlusterFS Volume"
       required: true
       type: "string"
       default: gv0
     - variable: "GLUSTERFS_SERVERS"
       label: "GlusterFS Servers"
       type: "string"
       required: true
       description: Servers' name for GlusterFS, separate by comma

convoy-gluster:
    metadata:
        volume_pool: "${VOLUME_POOL}"
        glusterfs_servers: "${GLUSTERFS_SERVERS}"
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

convoy-gluster-storagepool:
    scale: 1
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
